import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Showprep",
  description: "Terms of Service for Showprep",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl prose prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: March 16, 2025</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using Showprep (&quot;Service&quot;), you agree to be bound by these
        Terms of Service. If you do not agree, do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Showprep is a service that helps podcasters and creators stay on top of
        their YouTube subscriptions by providing AI-generated article summaries and
        audio gencasts from video content. The Service requires you to sign in with
        your YouTube/Google account to access your subscriptions and deliver
        personalized content.
      </p>

      <h2>3. Account and YouTube Sign-In</h2>
      <p>
        You must sign in with a valid YouTube/Google account to use the Service.
        You are responsible for maintaining the security of your account. You must
        comply with Google&apos;s Terms of Service and YouTube Terms of Service when
        using the Service.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any illegal purpose or in violation of any laws</li>
        <li>Abuse, harass, or harm other users</li>
        <li>Attempt to gain unauthorized access to the Service or related systems</li>
        <li>Use the Service to infringe any third-party rights, including intellectual property</li>
        <li>Resell or redistribute the Service without authorization</li>
      </ul>

      <h2>5. Intellectual Property and Content</h2>
      <p>
        The Service and its original content (excluding user-generated content and
        third-party content) are owned by Showprep. Content generated by the
        Service (summaries, gencasts) is provided for your personal use. You retain
        rights to content you create. By using the Service, you grant us a license
        to use, store, and display your content as necessary to operate the Service.
      </p>

      <h2>6. Disclaimer</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE
        DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED. WE DO NOT GUARANTEE
        ACCURACY, COMPLETENESS, OR RELIABILITY OF GENERATED CONTENT.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHOWPREP AND ITS AFFILIATES SHALL
        NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
        PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR DATA, ARISING FROM YOUR USE OF
        THE SERVICE.
      </p>

      <h2>8. Termination</h2>
      <p>
        We may suspend or terminate your access to the Service at any time for
        violation of these Terms or for any other reason. You may stop using the
        Service and disconnect your YouTube account at any time.
      </p>

      <h2>9. Governing Law</h2>
      <p>
        These Terms shall be governed by the laws of the jurisdiction in which
        Showprep operates, without regard to conflict of law principles.
      </p>

      <h2>10. Contact</h2>
      <p>
        For questions about these Terms, please contact us at the email address
        provided in the Showprep application or on our website.
      </p>

      <p className="mt-8">
        <Link href="/" className="text-primary hover:underline">
          Back to Showprep
        </Link>
      </p>
    </div>
  );
}
